// Supabase Client - Auto-generated by Backend Service
// DO NOT import supabase directly for authenticated operations
// Use the useSupabase() hook instead to ensure proper authentication

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
const hasSupabaseConfig = Boolean(supabaseUrl && supabaseAnonKey);

const fallbackUrl = 'https://example.supabase.co';
const fallbackAnonKey = 'missing-supabase-anon-key';

if (!hasSupabaseConfig && typeof window !== 'undefined') {
  console.warn(
    '[Supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY. ' +
    'Using fallback client so the UI can render.'
  );
}

// Base client - for public/unauthenticated queries only
export const supabase = createClient(
  hasSupabaseConfig ? supabaseUrl : fallbackUrl,
  hasSupabaseConfig ? supabaseAnonKey : fallbackAnonKey
);

// Factory for authenticated client - used by useSupabase() hook
export function createAuthenticatedClient(accessToken) {
  const client = createClient(
    hasSupabaseConfig ? supabaseUrl : fallbackUrl,
    hasSupabaseConfig ? supabaseAnonKey : fallbackAnonKey,
    {
    global: {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    },
    }
  );

  // Authenticate the realtime WebSocket connection for RLS to work
  client.realtime.setAuth(accessToken);

  return client;
}
